version: "3"

services:
  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    expose:
      - "7000"
    ports:
      - "7000:7000"
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    expose:
      - "7001"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-2:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker-2
    depends_on:
      - spark-master
    expose:
      - "7002"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - INIT_DAEMON_STEP=setup_spark
